Upgrade to Bevy 0.17
fails with:

thread 'main' (20058254) panicked at /Users/aw/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-26.0.1/src/backend/wgpu_core.rs:1327:26:
wgpu error: Validation Error

Caused by:
  In Device::create_render_pipeline, label = 'opaque_mesh_pipeline'
    Error matching ShaderStages(VERTEX) shader requirements against the pipeline
      Shader global ResourceBinding { group: 2, binding: 0 } is not available in the pipeline layout
        Storage class Uniform doesn't match the shader Storage { access: StorageAccess(LOAD) }